a = float (input("Введите а = "))
b = float (input("Введите b = "))
print ("Сумма =", a + b, end="\n")
print ("Разность =", a - b, end="\n")
print ("Произведение =", (a * b), end="\n")
print ("Возведение a в степень b =", (a ** b), end="\n")
print ("Делить по модулю =", (a / b), end="\n")
print ("Целочисленное деление a на b =", (a // b), end="\n")
